import java.lang.Exception


fun main(args: Array<String>) {
val teach1= MathTeacher()
    teach1.teachMath()

    val teach2=EngTeacher()
    teach2.teachEng()
//    val car1 = Lambo()
//    car1.driveLambo()
//
//    val car2 = Mers()
//    car2.driveMers()
// val firstList = listOf(10,43,54,32,23)
//
//    val secondList = listOf(43,342 ,234,64,45)
//
//
//    firstList.forEachIndexed { index, num ->
//
//        val sum = num + secondList[index]
//
//        println("sum of index $index is $sum")
//    }







}















